package com.yuzeduan.lovesong.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yuzeduan.lovesong.recommend.bean.AlbumList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALBUM_LIST".
*/
public class AlbumListDao extends AbstractDao<AlbumList, Long> {

    public static final String TABLENAME = "ALBUM_LIST";

    /**
     * Properties of entity AlbumList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MAlbumId = new Property(1, String.class, "mAlbumId", false, "mAlbumId");
        public final static Property MTitle = new Property(2, String.class, "mTitle", false, "mTitle");
        public final static Property MAuthor = new Property(3, String.class, "mAuthor", false, "mAuthor");
        public final static Property MPicPath = new Property(4, String.class, "mPicPath", false, "mPicPath");
        public final static Property MPublishTime = new Property(5, String.class, "mPublishTime", false, "mPublishTime");
    }


    public AlbumListDao(DaoConfig config) {
        super(config);
    }
    
    public AlbumListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALBUM_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"mAlbumId\" TEXT," + // 1: mAlbumId
                "\"mTitle\" TEXT," + // 2: mTitle
                "\"mAuthor\" TEXT," + // 3: mAuthor
                "\"mPicPath\" TEXT," + // 4: mPicPath
                "\"mPublishTime\" TEXT);"); // 5: mPublishTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALBUM_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AlbumList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mAlbumId = entity.getMAlbumId();
        if (mAlbumId != null) {
            stmt.bindString(2, mAlbumId);
        }
 
        String mTitle = entity.getMTitle();
        if (mTitle != null) {
            stmt.bindString(3, mTitle);
        }
 
        String mAuthor = entity.getMAuthor();
        if (mAuthor != null) {
            stmt.bindString(4, mAuthor);
        }
 
        String mPicPath = entity.getMPicPath();
        if (mPicPath != null) {
            stmt.bindString(5, mPicPath);
        }
 
        String mPublishTime = entity.getMPublishTime();
        if (mPublishTime != null) {
            stmt.bindString(6, mPublishTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AlbumList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mAlbumId = entity.getMAlbumId();
        if (mAlbumId != null) {
            stmt.bindString(2, mAlbumId);
        }
 
        String mTitle = entity.getMTitle();
        if (mTitle != null) {
            stmt.bindString(3, mTitle);
        }
 
        String mAuthor = entity.getMAuthor();
        if (mAuthor != null) {
            stmt.bindString(4, mAuthor);
        }
 
        String mPicPath = entity.getMPicPath();
        if (mPicPath != null) {
            stmt.bindString(5, mPicPath);
        }
 
        String mPublishTime = entity.getMPublishTime();
        if (mPublishTime != null) {
            stmt.bindString(6, mPublishTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AlbumList readEntity(Cursor cursor, int offset) {
        AlbumList entity = new AlbumList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mAlbumId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mTitle
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mAuthor
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mPicPath
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // mPublishTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AlbumList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMAlbumId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMPicPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMPublishTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AlbumList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AlbumList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AlbumList entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
