package com.yuzeduan.lovesong.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yuzeduan.lovesong.songlist.bean.AlbumInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALBUM_INFO".
*/
public class AlbumInfoDao extends AbstractDao<AlbumInfo, Long> {

    public static final String TABLENAME = "ALBUM_INFO";

    /**
     * Properties of entity AlbumInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MAuthor = new Property(1, String.class, "mAuthor", false, "mAuthor");
        public final static Property MLrclink = new Property(2, String.class, "mLrclink", false, "mLrclink");
        public final static Property MSongId = new Property(3, String.class, "mSongId", false, "mSongId");
        public final static Property MTitle = new Property(4, String.class, "mTitle", false, "mTitle");
        public final static Property MAlbumId = new Property(5, String.class, "mAlbumId", false, "mAlbumId");
    }


    public AlbumInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AlbumInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALBUM_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"mAuthor\" TEXT," + // 1: mAuthor
                "\"mLrclink\" TEXT," + // 2: mLrclink
                "\"mSongId\" TEXT," + // 3: mSongId
                "\"mTitle\" TEXT," + // 4: mTitle
                "\"mAlbumId\" TEXT);"); // 5: mAlbumId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALBUM_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AlbumInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mAuthor = entity.getMAuthor();
        if (mAuthor != null) {
            stmt.bindString(2, mAuthor);
        }
 
        String mLrclink = entity.getMLrclink();
        if (mLrclink != null) {
            stmt.bindString(3, mLrclink);
        }
 
        String mSongId = entity.getMSongId();
        if (mSongId != null) {
            stmt.bindString(4, mSongId);
        }
 
        String mTitle = entity.getMTitle();
        if (mTitle != null) {
            stmt.bindString(5, mTitle);
        }
 
        String mAlbumId = entity.getMAlbumId();
        if (mAlbumId != null) {
            stmt.bindString(6, mAlbumId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AlbumInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mAuthor = entity.getMAuthor();
        if (mAuthor != null) {
            stmt.bindString(2, mAuthor);
        }
 
        String mLrclink = entity.getMLrclink();
        if (mLrclink != null) {
            stmt.bindString(3, mLrclink);
        }
 
        String mSongId = entity.getMSongId();
        if (mSongId != null) {
            stmt.bindString(4, mSongId);
        }
 
        String mTitle = entity.getMTitle();
        if (mTitle != null) {
            stmt.bindString(5, mTitle);
        }
 
        String mAlbumId = entity.getMAlbumId();
        if (mAlbumId != null) {
            stmt.bindString(6, mAlbumId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AlbumInfo readEntity(Cursor cursor, int offset) {
        AlbumInfo entity = new AlbumInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mAuthor
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mLrclink
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mSongId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mTitle
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // mAlbumId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AlbumInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMAuthor(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMLrclink(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMSongId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMAlbumId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AlbumInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AlbumInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AlbumInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
