package com.yuzeduan.lovesong.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yuzeduan.lovesong.recommend.bean.AlbumList;
import com.yuzeduan.lovesong.recommend.bean.FocusPic;
import com.yuzeduan.lovesong.recommend.bean.HotSongList;
import com.yuzeduan.lovesong.recommend.bean.RadioList;
import com.yuzeduan.lovesong.search.bean.HotWord;
import com.yuzeduan.lovesong.songlist.bean.AlbumInfo;
import com.yuzeduan.lovesong.songlist.bean.SongInfoJsonBean;

import com.yuzeduan.lovesong.db.AlbumListDao;
import com.yuzeduan.lovesong.db.FocusPicDao;
import com.yuzeduan.lovesong.db.HotSongListDao;
import com.yuzeduan.lovesong.db.RadioListDao;
import com.yuzeduan.lovesong.db.HotWordDao;
import com.yuzeduan.lovesong.db.AlbumInfoDao;
import com.yuzeduan.lovesong.db.SongInfoJsonBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig albumListDaoConfig;
    private final DaoConfig focusPicDaoConfig;
    private final DaoConfig hotSongListDaoConfig;
    private final DaoConfig radioListDaoConfig;
    private final DaoConfig hotWordDaoConfig;
    private final DaoConfig albumInfoDaoConfig;
    private final DaoConfig songInfoJsonBeanDaoConfig;

    private final AlbumListDao albumListDao;
    private final FocusPicDao focusPicDao;
    private final HotSongListDao hotSongListDao;
    private final RadioListDao radioListDao;
    private final HotWordDao hotWordDao;
    private final AlbumInfoDao albumInfoDao;
    private final SongInfoJsonBeanDao songInfoJsonBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumListDaoConfig = daoConfigMap.get(AlbumListDao.class).clone();
        albumListDaoConfig.initIdentityScope(type);

        focusPicDaoConfig = daoConfigMap.get(FocusPicDao.class).clone();
        focusPicDaoConfig.initIdentityScope(type);

        hotSongListDaoConfig = daoConfigMap.get(HotSongListDao.class).clone();
        hotSongListDaoConfig.initIdentityScope(type);

        radioListDaoConfig = daoConfigMap.get(RadioListDao.class).clone();
        radioListDaoConfig.initIdentityScope(type);

        hotWordDaoConfig = daoConfigMap.get(HotWordDao.class).clone();
        hotWordDaoConfig.initIdentityScope(type);

        albumInfoDaoConfig = daoConfigMap.get(AlbumInfoDao.class).clone();
        albumInfoDaoConfig.initIdentityScope(type);

        songInfoJsonBeanDaoConfig = daoConfigMap.get(SongInfoJsonBeanDao.class).clone();
        songInfoJsonBeanDaoConfig.initIdentityScope(type);

        albumListDao = new AlbumListDao(albumListDaoConfig, this);
        focusPicDao = new FocusPicDao(focusPicDaoConfig, this);
        hotSongListDao = new HotSongListDao(hotSongListDaoConfig, this);
        radioListDao = new RadioListDao(radioListDaoConfig, this);
        hotWordDao = new HotWordDao(hotWordDaoConfig, this);
        albumInfoDao = new AlbumInfoDao(albumInfoDaoConfig, this);
        songInfoJsonBeanDao = new SongInfoJsonBeanDao(songInfoJsonBeanDaoConfig, this);

        registerDao(AlbumList.class, albumListDao);
        registerDao(FocusPic.class, focusPicDao);
        registerDao(HotSongList.class, hotSongListDao);
        registerDao(RadioList.class, radioListDao);
        registerDao(HotWord.class, hotWordDao);
        registerDao(AlbumInfo.class, albumInfoDao);
        registerDao(SongInfoJsonBean.class, songInfoJsonBeanDao);
    }
    
    public void clear() {
        albumListDaoConfig.clearIdentityScope();
        focusPicDaoConfig.clearIdentityScope();
        hotSongListDaoConfig.clearIdentityScope();
        radioListDaoConfig.clearIdentityScope();
        hotWordDaoConfig.clearIdentityScope();
        albumInfoDaoConfig.clearIdentityScope();
        songInfoJsonBeanDaoConfig.clearIdentityScope();
    }

    public AlbumListDao getAlbumListDao() {
        return albumListDao;
    }

    public FocusPicDao getFocusPicDao() {
        return focusPicDao;
    }

    public HotSongListDao getHotSongListDao() {
        return hotSongListDao;
    }

    public RadioListDao getRadioListDao() {
        return radioListDao;
    }

    public HotWordDao getHotWordDao() {
        return hotWordDao;
    }

    public AlbumInfoDao getAlbumInfoDao() {
        return albumInfoDao;
    }

    public SongInfoJsonBeanDao getSongInfoJsonBeanDao() {
        return songInfoJsonBeanDao;
    }

}
