package com.yuzeduan.lovesong.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yuzeduan.lovesong.songlist.bean.SongInfoJsonBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SONG_INFO_JSON_BEAN".
*/
public class SongInfoJsonBeanDao extends AbstractDao<SongInfoJsonBean, Long> {

    public static final String TABLENAME = "SONG_INFO_JSON_BEAN";

    /**
     * Properties of entity SongInfoJsonBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MSongId = new Property(1, String.class, "mSongId", false, "mSongId");
        public final static Property MJsonData = new Property(2, String.class, "mJsonData", false, "mJsonData");
    }


    public SongInfoJsonBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SongInfoJsonBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SONG_INFO_JSON_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"mSongId\" TEXT," + // 1: mSongId
                "\"mJsonData\" TEXT);"); // 2: mJsonData
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SONG_INFO_JSON_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SongInfoJsonBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mSongId = entity.getMSongId();
        if (mSongId != null) {
            stmt.bindString(2, mSongId);
        }
 
        String mJsonData = entity.getMJsonData();
        if (mJsonData != null) {
            stmt.bindString(3, mJsonData);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SongInfoJsonBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mSongId = entity.getMSongId();
        if (mSongId != null) {
            stmt.bindString(2, mSongId);
        }
 
        String mJsonData = entity.getMJsonData();
        if (mJsonData != null) {
            stmt.bindString(3, mJsonData);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SongInfoJsonBean readEntity(Cursor cursor, int offset) {
        SongInfoJsonBean entity = new SongInfoJsonBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mSongId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // mJsonData
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SongInfoJsonBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMSongId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMJsonData(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SongInfoJsonBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SongInfoJsonBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SongInfoJsonBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
